apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
  labels:
    app: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            - name: REDIS_URI
              valueFrom:
                configMapKeyRef:
                  name: app-env-configmap
                  key: REDIS_URI
